---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pulumi-operator
  namespace: pulumi
spec:
  values:
    operator:
      logLevel: warn  # Minimal logging for production
      # Full resources for production environment
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 256Mi
    # Enable monitoring in production
    serviceMonitor:
      enabled: true
