---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulumi-operator
  namespace: pulumi
spec:
  template:
    spec:
      containers:
        - name: manager
          # Full resources for production environment
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          env:
            - name: PULUMI_LOG_LEVEL
              value: "warn"  # Minimal logging for production
