---
apiVersion: v1
kind: Namespace
metadata:
  name: pulumi
  labels:
    app.kubernetes.io/name: pulumi-operator
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: programs.pulumi.com
spec:
  group: pulumi.com
  names:
    kind: Program
    listKind: ProgramList
    plural: programs
    singular: program
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: updates.auto.pulumi.com
spec:
  group: auto.pulumi.com
  names:
    kind: Update
    listKind: UpdateList
    plural: updates
    singular: update
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: stacks.pulumi.com
spec:
  group: pulumi.com
  names:
    kind: Stack
    listKind: StackList
    plural: stacks
    singular: stack
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workspaces.auto.pulumi.com
spec:
  group: auto.pulumi.com
  names:
    kind: Workspace
    listKind: WorkspaceList
    plural: workspaces
    singular: workspace
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulumi-operator
  namespace: pulumi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulumi-operator-manager
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - secrets
      - configmaps
      - persistentvolumeclaims
      - events
    verbs: ["*"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
    verbs: ["*"]

  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["*"]

  - apiGroups: ["pulumi.com"]
    resources:
      - stacks
      - programs
      - stacks/status
      - programs/status
      - stacks/finalizers
      - programs/finalizers
    verbs: ["*"]
  
  - apiGroups: ["auto.pulumi.com"]
    resources:
      - updates
      - workspaces
      - updates/status
      - workspaces/status
      - updates/finalizers
      - workspaces/finalizers
    verbs: ["*"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs: ["*"]

  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["*"]

  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["*"]

  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs: ["*"]

  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["*"]

  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["*"]

  - apiGroups: ["cert-manager.io"]
    resources:
      - certificates
      - certificaterequests
      - clusterissuers
      - issuers
    verbs: ["*"]

  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pulumi-operator-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pulumi-operator-manager
subjects:
- kind: ServiceAccount
  name: pulumi-operator
  namespace: pulumi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulumi-operator
  namespace: pulumi
  labels:
    app.kubernetes.io/name: pulumi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pulumi-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pulumi-operator
    spec:
      serviceAccountName: pulumi-operator
      containers:
      - name: manager
        image: pulumi/pulumi-kubernetes-operator:v2.1.0
        args:
        - "/manager"
        - "--leader-elect"
        env:
        - name: PULUMI_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: pulumi-access-token
              key: PULUMI_ACCESS_TOKEN
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
