---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pulumi-operator
  namespace: pulumi
spec:
  values:
    operator:
      logLevel: info  # Less verbose logging for staging
      # Moderate resources for staging environment
      resources:
        limits:
          cpu: 400m
          memory: 400Mi
        requests:
          cpu: 75m
          memory: 96Mi
    # Enable monitoring in staging
    serviceMonitor:
      enabled: true
